title: "Royfactory"
description: "개발, AI, Kubernetes, 백엔드 기술 블로그"
url: "https://royfactory.github.io"
baseurl: ""
lang: "ko"

theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-archives

paginate: 10
paginate_path: "/page:num/"

author:
  name: "Roy"
  email: "worry1318@naver.com"

social:
  name: "Royfactory Blog"
  links:
    - "https://github.com/royfactory"
    - "https://royzero.tistory.com/"

sitemap:
  exclude:
    - /assets/
    - /_sass/
  include_posts: true
