baseURL = 'https://royfactory.net'
languageCode = 'ko'
title = 'Royfactory'
description = 'Development, AI, Kubernetes, and Backend Technology Blog'
canonifyURLs = true
relativeURLs = false
enableRobotsTXT = true
enableGitInfo = true
disablePathToLower = true

# Theme
theme = 'PaperMod'

# Frontmatter lastmod 우선순위 설정
[frontmatter]
  lastmod = [":git", "lastmod", "date", "publishDate"]

# Params
[params]
  author = 'Roy'
  description = 'Development, AI, Kubernetes, and Backend Technology Blog'
  keywords = ['AI', 'Kubernetes', 'Backend', 'Development', 'Blog']
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowToc = true
  TocOpen = false
  comments = false
  
  # Archive settings - 모든 포스트를 archive 페이지에 표시
  ShowAllPagesInArchive = true
  mainSections = ["posts"]
  
  # Google AdSense
  googleAdsense = "7151406524991928"
  
  # Assets and Icons
  [params.assets]
    favicon = "/favicon.ico"
    favicon16x16 = "/favicon-16x16.png"
    favicon32x32 = "/favicon-32x32.png"
    apple_touch_icon = "/apple-touch-icon.png"

[params.homeInfoParams]
  Title = "Welcome to Royfactory"
  Content = "Latest articles on Development, AI, Kubernetes, and Backend Technologies."

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/royfactory"

[[params.socialIcons]]
  name = "tistory"
  url = "https://royzero.tistory.com/"

# Menu
[menu]
  [[menu.main]]
    identifier = "archive"
    name = "Archive"
    url = "/archive/"
    weight = 10
  
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 20
  
  [[menu.main]]
    identifier = "apps"
    name = "Apps"
    url = "/apps/"
    weight = 30

# Taxonomies
[taxonomies]
  tag = "tags"
  category = "categories"

# Markup
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false
    codeFences = true
    guessSyntax = true
    lineNos = true
    style = "github"
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

# Outputs - 태그/카테고리 페이지 사이트맵에서 제외
[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML"]
  term = ["HTML"]

# Sitemap
[sitemap]
  changefreq = 'weekly'
  filename = 'sitemap.xml'
  priority = 0.5

# Privacy
[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = false
    respectDoNotTrack = true
  [privacy.instagram]
    disable = true
  [privacy.x]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = false
    privacyEnhanced = true
